### ISSUE TITLE
No packets on the Expo implementation

### ISSUE THREAD

**Issue by lucabellintani** [inthepocket/react-native-service-discovery#1]
Hi, I am running Expo 6.3.10. I have been trying to use the latest version of your library 0.2.0 without success.
The example code you provide compiles without errors on Expo Development Build but when I execute the app on Android it won't generate any packets. I have been running some network sniffers just to confirm the behavior.

**Issue Summary:**
The app initiates a scan using the startServiceScan function from the network scanning library but does not generate or detect any network packets.

**Reproduction Steps:**
Call the startServiceScan function within the handleScan function in App.js.
The scanning process is indicated by isScanning being set to true, and a 20-second timeout is set to reset the scanning state.
Upon initiating startServiceScan, no network packets appear to be generated or detected.

**Expected Behavior:**
After calling startServiceScan, I expect to see network packets generated, suggesting an active scan process is taking place.

**Actual Behavior:**
Despite the isScanning state indicating that the scan is running, there is no evidence of network packets generated or detected throughout the scanning period. Additionally, no errors or console logs are provided to suggest a failure within the function call.

**Error Logging:**
There are no errors directly thrown by startServiceScan, and the promise resolves without issue. However, packet generation is not observed, suggesting a potential silent failure or incomplete execution within the library itself.  

**My question is: Has this library ever been tested in Expo? Are there any special settings needed?**

For reference this is the code I used in the test:
```
// service_scan.tsx
import * as ServiceDiscovery from '@inthepocket/react-native-service-discovery';

export const startServiceScan = async () => {
  // Add event listeners for service discovery
  const foundListener = ServiceDiscovery.addEventListener('serviceFound', (service) => {
    console.log('Service found:', service);
    });

  const lostListener = ServiceDiscovery.addEventListener('serviceLost', (service) => {
    console.log('Service lost:', service);
  });

  try {
    console.log("Starting service search for HTTP and SSH...");
    await ServiceDiscovery.startSearch('');

    // Stop search after 20 seconds
    setTimeout(async () => {
      console.log("Stopping service search after timeout...");
      await ServiceDiscovery.stopSearch('');
      foundListener.remove();
      lostListener.remove();
      console.log("Service search stopped.");
    }, 20000); // Run scan for 20 seconds
  } catch (error) {
    console.error("Error during service scan:", error);
  }
};
 
```

**Comment by robrechtme** [comment]
Hi @lucabellintani! Are you sure you are running Expo 6.3.10? The latest version is 51. Secondly, you need to specify _which_ services you want to discover, e.g. 
```typescript
await ServiceDiscovery.startSearch('ssh');
```

An empty string won't do much here.

**Comment by lucabellintani** [comment]
Ah! thanks. First: apologies for the version; I shared with you the Expo CLI version. The Expo version is in fact 51.0.28.  About the empty parameters: is there an option to use a wildcard instead? What I am after is collect any service shared by any device in my network. If not, how can I get a full list of valid services?

**Comment by robrechtme** [comment]
There is no wildcard option as iOS does not support this unfortunately. You can find a list of popular services [here](https://jonathanmumm.com/tech-it/mdns-bonjour-bible-common-service-strings-for-various-vendors/), but know that the list is not exhaustive because any string can be used to advertise.

**Comment by lucabellintani** [comment]
That is a super useful information. Many thanks for the library and your great support!

**Comment by lucabellintani** [comment]
Problem solved. Great support.
